# Site wide configuration

title: "Mint Digital Revolutions"
description: "Coming Soon"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: Miralda Sanchez

#Target date in UTC / GMT
countdown: UTC / GMT
  theme: red
  year: 2019
  month: 9
  day: 8
  hour: 3
  minute: 25

# Site owner
  owner: Miralda Sanchez
  name: Mint Digital Revolutions
  email: miralda.ixein6.go4dkill@gmail.com
  twitter: @xein6
  facebook: Miralda Sanchez
  instagram: miraldaxein6
  linkedln: Miralda Sanchez
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  
   
    


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
